---
#
# Configuration file for 'dns_powerdns' dns provider
#

# use these settings for powerdns
#:powerdns_mysql_hostname:
#:powerdns_mysql_username:
#:powerdns_mysql_password:
#:powerdns_mysql_database:
